apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#namespace: app1
#namePrefix: dev-

resources:
- frontend.yml
- backend.yml
- database.yml

configMapGenerator:
- name: db-config-map
  files: 
  - init.sql